"""empty message

Revision ID: 757e7e965013
Revises: 
Create Date: 2021-10-31 22:01:46.376965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757e7e965013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ORIGINAL_LINK', sa.String(length=100), nullable=True),
    sa.Column('SHORTEN_LINK', sa.String(length=50), nullable=True),
    sa.Column('DATE', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
